### PR TITLE
M1: First stage bootloader

### PR DESCRIPTION
**Pull request by VinDuv**
Add a ROM memory region at physical address 0, which handles setting up the registers and jumping to the firmware’s entry point. This avoids having to use a CPU reset handler to do this task.

The memory region is initialized with pre-compiled code (`m1boot.bin`) from the `pc-bios` directory, whose sources are stored in the `roms` directory. This seems to match existing practices.

Setting the `HCR_EL2` register from the emulated code also fixes some issues: the previous method of setting it directly in the reset handler caused an assertion failure in the debug version of qemu (`TCG hflags mismatch (current:0x8e100000 rebuilt:0x8b204000)`).
However, it only sets the register to `0x488000000`; bits 40 and 41 (`HCR_APK` and `HCR_API` according to m1n1’s sources) are ignored. I’ll try to find out why before completing this PR.

### CODE REVIEW

**Comment by Lunaphied** [comment]
A few notes about my thoughts for how into initialization should work (note I've edited this based on some thoughts I had in the comment that follows)

The reason for that is that Linux for the M1 will expect to be booted from m1n1 or something like it, I believe the support for (I think it's OpenBSD) is using m1n1 to load u-boot which then will take on some required functionality. In the future there's reason to suspect that Linux will end up calling back into m1n1 to essentially abstract out some firmware logic that normally ARM chips handle but Apple just codes support for the implementation defined logic directly since they don't need to abstract.

Since M1N1 will likely be required to get Linux to play nice anyway, we probably would want it packaged with the qemu build if possible. (Hopefully there's no license issues that's a to-do for me which might change plans).

The second point is about the HCR register, it probably shouldn't be set via the boot stub since it actually requires special handling. For one, the M1 has E2H forced on and it cannot be disabled on real hardware, so that bit and possibly others will need to be read only. For another I already know that that register gets locked down once GXF is enabled and becomes restricted to GXF mode. Both will probably require changing some guts for TCG stuff so that I can special case HCR. Which will likely be a huge mess. Hence why for now it's hacked into reset.

The TCG error is interesting, what flags did you use to get that?

**Comment by Lunaphied** [comment]
Looking at the code I don't think my concerns are a big deal right now anyway, there is one point I think worth considering.

The other code that uses these short little stubs (for instance the SMP stubs for the raspberry Pi), embeds them in the platform with documentation. I think that's probably a better model to emulate here since it also avoids adding a dependency on an aarch64 compiler along with ensuring that everything is at the proper offsets.

The hw/arm/boot.c file has some helpers I believe (or maybe the Pi code just made those I can't remember). I know that upstream recently fleshed out helpers for I think PPC machines to make building those stubs easier too, so I think that's a better path here.

The reason for a full stub would be if it was needing to embed a full MachO loader. I'm still not sure how I want to handle that but I suspect making MachO loading happen on the host side is ultimately better.

**Comment by VinDuv** [comment]
To be clear, I have no idea how much more complicated this bootloader (or reset handler) will need to become in the future. I chose to put it in a separate ROM file to make future updates to it easier. However, if you think it isn’t expected to get very large/complicated, embedding it directly in `apple-m1.c` may be a simpler option.

(Note that the bootloader file `m1boot.bin` is directly stored in the Git repository, and is not recompiled by default, so no extra dependency is needed; the same approach seems to be used for other ROM files)

> The second point is about the HCR register, it probably shouldn't be set via the boot stub since it actually requires special handling. For one, the M1 has E2H forced on and it cannot be disabled on real hardware, so that bit and possibly others will need to be read only. For another I already know that that register gets locked down once GXF is enabled and becomes restricted to GXF mode. Both will probably require changing some guts for TCG stuff so that I can special case HCR. Which will likely be a huge mess. Hence why for now it's hacked into reset.

I’ll check this, but it looks like you can get qemu’s internal `HCR_EL2` handler with `get_arm_cp_reginfo` (`hcr_write` if I’m not mistaken). Maybe calling its `.writefn` (`hcr_write`) from the reset handler would work and not result in a failed assert afterwards?
(I guess this would also be useful for GXF, because you could override this handler with one that does nothing, for instance)

> The TCG error is interesting, what flags did you use to get that?

`configure --enable-debug`. It seems to enable `CONFIG_DEBUG_TCG`, which enables the assertion in `target/arm/helper.c:assert_hflags_rebuild_correctly`.

**Comment by Lunaphied** [comment]
> To be clear, I have no idea how much more complicated this bootloader (or reset handler) will need to become in the future. I chose to put it in a separate ROM file to make future updates to it easier. However, if you think it isn’t expected to get very large/complicated, embedding it directly in `apple-m1.c` may be a simpler option.
> 
> (Note that the bootloader file `m1boot.bin` is directly stored in the Git repository, and is not recompiled by default, so no extra dependency is needed; the same approach seems to be used for other ROM files)
> 
Ah I didn't realize that the binaries were kept around too. I don't expect us to need anything more complex than what the raspi or boot.c code currently does unless my understanding of the extent of iBoot's functionality changes. The only functionality I'm aware of it providing is the hardware init that's not relevant here and authenticating and loading the MachO kernel image.

> > The second point is about the HCR register, it probably shouldn't be set via the boot stub since it actually requires special handling. For one, the M1 has E2H forced on and it cannot be disabled on real hardware, so that bit and possibly others will need to be read only. For another I already know that that register gets locked down once GXF is enabled and becomes restricted to GXF mode. Both will probably require changing some guts for TCG stuff so that I can special case HCR. Which will likely be a huge mess. Hence why for now it's hacked into reset.
> 
> I’ll check this, but it looks like you can get qemu’s internal `HCR_EL2` handler with `get_arm_cp_reginfo` (`hcr_write` if I’m not mistaken). Maybe calling its `.writefn` (`hcr_write`) from the reset handler would work and not result in a failed assert afterwards?
> (I guess this would also be useful for GXF, because you could override this handler with one that does nothing, for instance)

I poked around this code a bit to try and remember why I handled HCR like I did. I think what will have to happen is that override versions of the registers that need special handling for things like GXF will need to be defined. Then those implementations can handle masking out bits or erroring. QEMU kind of does something like this for how it handles the E2H EL1->EL2 aliases.

Another model could be to define separate SPRR, E2H_FORCED, and GXF features (or combine them into an APPLE feature), then these feature bits could be used to change the definitions for affected registers and functions.

I think yet another option is to modify code paths based on CPU model registers. I think every single one of these approaches exists in some form in the current code. 

I'm not really sure what option is best. Regardless of the path taken some significant modifications to existing core arm target code will be required to support even just SPRR much less GXF.

> > The TCG error is interesting, what flags did you use to get that?
> 
> `configure --enable-debug`. It seems to enable `CONFIG_DEBUG_TCG`, which enables the assertion in `target/arm/helper.c:assert_hflags_rebuild_correctly`.

I'm assuming this is probably because I am enabling bits that the CPU model registers don't declare feature support for. It might also break out some of the bits into easier to manage forms that then don't match when I fuss with the register.

Something interesting to note is that the existing code (I think it's in hw/arm/boot.c) actually uses a CPU reset hook to tweak some HCR bits too.

**Comment by Lunaphied** [comment]
> > > The TCG error is interesting, what flags did you use to get that?
> > 
> > `configure --enable-debug`. It seems to enable `CONFIG_DEBUG_TCG`, which enables the assertion in `target/arm/helper.c:assert_hflags_rebuild_correctly`.

I think calling `arm_rebuild_hflags` after changing register definitions should resolve this.

**Comment by VinDuv** [comment]
After some more testing, I verified that the `HCR_EL2` handler has indeed nothing to do with the failed assert. `hw/arm/boot.c` touches the register manually, and that works (no failed assert) because it calls `arm_rebuild_hflags(env);` afterwards.

Setting the register via its write handler can be done with:
```
uint32_t hcr_el2_enc = ENCODE_AA64_CP_REG(CP_REG_ARM64_SYSREG_CP, 1, 1, 3, 4, 0);
const ARMCPRegInfo *hcr_el2_info = get_arm_cp_reginfo(cpu->cp_regs, hcr_el2_enc);
hcr_el2_info->writefn(&cpu->env, hcr_el2_info, 0x30488000000);
```
But it still causes the assert to fail unless`arm_rebuild_hflags(env); `. It however sets the register to `0x488000000`, as a real `msr` would have done.

The reason `HCR_APK` and `HCR_API` are missing is that [the write handler checks for pointer auth support](https://github.com/modwizcode/qemu/blob/add_M1_test/target/arm/helper.c#L5326). Adding `cpu->prop_pauth = true;` to `apple_firestorm_initfn` fixes it (I’m not completely sure if that’s the right way to do it though; there are no many examples in qemu’s code since only the “max” CPU type seems to handle this feature)

So at this point I think that having a bootloader that set the registers is probably not necessary, but I’m still a bit wary about setting them directly since it bypasses the internal checks. Maybe we should set them by calling the appropriate handler, and check that the correct value was indeed written? Or is it too paranoid?

**Comment by Lunaphied** [comment]
Ah thanks for looking into that, I think setting them in the reset handler is probably the way to go since that's how all the other code works, we just need to change our logic (or the checks but it sounds like in this case it's the init that I did that's not complete) to support it. It's likely that later I will use overrides or modify the logic bits to change what's registered so that the HCR register and others ignore bits that cannot be changed like the real hardware, at that point I can just define a new reset value and the code to set it elsewhere can be removed.

<details>
<summary>For background reference about <code>prop_pauth</code></summary>
<code>prop_pauth</code> sounds like the variable that a qemu object property would set so the correct way for that would be through setting the property, however most of the other features enabled this way also auto enable if you set the right cpu support bits so I suspect that's a better option.
</details>

The call to `arm_rebuild_hflags(env)` is required for sure, that's just an omission I made because I didn't test it in a way that triggered the assert and I think it doesn't actually change anything that would cause a fail. 

I don't think setting them via the handler like that the right path. Maybe I'm wrong and it's a fine way to do things, but my understanding is that for the most part those register functions are meant to be only used internally by the code to synthesize `msr`/`mrs` calls correctly. However it might be a better solution than how I currently handle the timer reads in the AIC (since those seem to match reading the `CNTPCT_EL0` register and there's no easy way to access it otherwise.

**Comment by VinDuv** [comment]
Okay. Since we’re going to keep the “simple” register setting in the reset handler, I’m going to close this PR.
I’ll open a separate one to add the missing `rebuild_hflags` and clarify the comment on the `hcr_el2` direct assignment.
I’ll also open an issue regarding the need to support pointer authentication.

**Pull request closed without merging**
